server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
  cloud:
    config:
      server:
        git:
#          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/tianshuang123/springcloud-config.git  #GitHub上复制的项目地址
          search-paths:  #搜索目录
            - springcloud-config
      label: main   #读取分支
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址